export const TRADES = "trades"
export const ACTIVE_TRADE = "activeTrade"
export const USER_ACCESS_KEY = "user_access"
export const USER_REFRESH_KEY = "user_refresh"

export const TOUR_DATA = "tour-data"
export const PLAN_BENEFIT = "plan-benefit"
export const USER_DATA = "user-data"
export const COUNTRY_DATA = "country-data"
export const CITY_DATA = "city-data"
export const ENTERANCE_DATA = "enterance-data"
export const TRANSPORT_DATA = "transport-data"
export const HOTEL_DATA = "hotel-data"
export const FOOD_DATA = "food-data"
export const CATEGORY_DATA = "category-data"
